### ISSUE TITLE
add premium client functionality

### ISSUE THREAD

**Issue by Japoivvb** [poksyy/poo_shop#1]
1. before ask for client name in sale option, include a new question about if the client is premium or not.

-    if the answer is No, continue flow as is

-    if the answer is Yes, 

       create a premiumClient object which extends from Client, 
	   it has a points attribute and its pay method is the same as parent client but for each 10€ sales, it adds 1 point. e.g. if sale 35€, premiumClient gets 3 points.
       show its points earned after the sale total amount
	   
2. set issue label as enhancement to be tracked

3. commit message with verb + #numberIssue + details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by poksyy** [comment]
Lines of code:
![1](https://github.com/poksyy/poo_shop/assets/153611745/e597c059-d949-46d2-8dac-d32abefe57b7)
Console output:
![2](https://github.com/poksyy/poo_shop/assets/153611745/0c868384-a69d-4ff4-84f9-465975cba48d)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
great job, you got +1 in UF4P1
